# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  body_converter:
    enabled: true
    validate: true
    validation_errors_argument: validationErrors
  body_listener:
    enabled: true
  view:
    view_response_listener: true
  serializer:
    serialize_null: true
  format_listener:
    rules:
      - {
          path: '^/api',
          prefer_extension: true,
          fallback_format: 'json',
          priorities: ['json'],
        }
      - {
          path: '^/',
          priorities: ['html', '*/*'],
          fallback_format: html,
          prefer_extension: true,
        }
  disable_csrf_role: ROLE_API
